version: "3.8"

networks:
    laravel:
        driver: bridge

services:
    nginx:
        container_name: "nginx_CGP"
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "${FORWARD_NGINX_PORT:-80}:80"
        volumes:
            - ./src:/var/www/html:delegated
        depends_on:
            - php
            - redis
            - mysql
        networks:
            - laravel

    mysql:
        container_name: "mysql_CGP"
        image: mariadb:11.6
        restart: unless-stopped
        tty: true
        ports:
            - "${FORWARD_MYSQL_PORT:-3314}:3306"
        volumes:
            - ./mysql:/var/lib/mysql:delegated
            - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            TZ: "Europe/Kyiv"
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            retries: 3
            timeout: 5s
            interval: 10s
        networks:
            - laravel

    php:
        container_name: "php_CGP"
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "${FORWARD_PHP_PORT:-9000}:9000"
        volumes:
            - ./src:/var/www/html:delegated
            - ./dockerfiles/configs/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - laravel

    phpmyadmin:
        container_name: "phpmyadmin_CGP"
        image: phpmyadmin:5.2
        restart: unless-stopped
        ports:
            - "${FORWARD_PHPMYADMIN_PORT:-8081}:80"
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: "${DB_PASSWORD}"
            UPLOAD_LIMIT: 64M
        depends_on:
            - mysql
        networks:
            - laravel

    redis:
        container_name: "redis_CGP"
        image: redis:7.4-alpine
        restart: unless-stopped
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
            interval: 10s
        networks:
            - laravel

    composer:
        container_name: "composer_CGP"
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - ./src:/var/www/html
        depends_on:
            - php
        entrypoint: ["composer", "--ignore-platform-reqs"]
        networks:
            - laravel

    npm:
        container_name: "npm_CGP"
        image: node:23-alpine
        volumes:
            - ./src:/var/www/html
        ports:
            - "${FORWARD_NPM_PORT:-3000}:3000"
        working_dir: /var/www/html
        entrypoint: ["npm"]
        networks:
            - laravel

    artisan:
        container_name: "artisan_CGP"
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - ./src:/var/www/html:delegated
        depends_on:
            - mysql
        entrypoint: ["php", "/var/www/html/artisan"]
        networks:
            - laravel